from fastapi import APIRouter
from typing import List
from masesora_backend.models.symptom_master import SymptomMaster
from masesora_backend.database.database import get_collection

router = APIRouter()

ALL_SYMPTOMS = [
  {
    "code": "UCI-S1",
    "label": "Hemorragia de Caja",
    "decision": "Corte de Sangrado",
    "decision_explanation": "Detener la pérdida inmediata de liquidez",
    "action": "Identificar gastos urgentes y detener fugas",
    "action_explanation": "Evita colapso financiero inmediato",
    "tool": "Mapa de Fugas",
    "tool_explanation": "Detecta dónde se pierde dinero",
    "master_decision": "Gobierno de Liquidez",
    "master_decision_explanation": "Controlar flujo vital del negocio",
    "master_action": "Diseñar sistema de control de caja",
    "master_action_explanation": "Evita recaídas y estabiliza finanzas",
    "master_tool": "Radar de Liquidez",
    "master_tool_explanation": "Monitorea salud financiera en tiempo real"
  },
  {
    "code": "UCI-S2",
    "label": "Paro Cardíaco Comercial",
    "decision": "Reanimación de Ventas",
    "decision_explanation": "Detectar ausencia de ingresos nuevos",
    "action": "Activar campaña de captación inmediata",
    "action_explanation": "Genera flujo comercial rápido",
    "tool": "Campaña RCP Comercial",
    "tool_explanation": "Acciones rápidas para reactivar ventas",
    "master_decision": "Dominio Comercial",
    "master_decision_explanation": "Sistema estable de captación",
    "master_action": "Diseñar motor comercial permanente",
    "master_action_explanation": "Evita dependencia de acciones puntuales",
    "master_tool": "Motor Comercial Maestro",
    "master_tool_explanation": "Sistema continuo de captación"
  },
  {
    "code": "UCI-S3",
    "label": "Asfixia Operativa",
    "decision": "Oxigenación de Procesos",
    "decision_explanation": "Detectar saturación operativa",
    "action": "Eliminar tareas no esenciales",
    "action_explanation": "Recupera capacidad operativa",
    "tool": "Mapa de Oxígeno",
    "tool_explanation": "Identifica tareas que ahogan la operación",
    "master_decision": "Flujo Operativo",
    "master_decision_explanation": "Sistema que respira sin saturarse",
    "master_action": "Rediseñar procesos críticos",
    "master_action_explanation": "Evita colapsos futuros",
    "master_tool": "Arquitectura de Flujo",
    "master_tool_explanation": "Diseño maestro de procesos"
  },
  {
    "code": "UCI-S4",
    "label": "Colapso de Agenda",
    "decision": "Liberación de Capacidad",
    "decision_explanation": "Detectar saturación del dueño",
    "action": "Eliminar tareas no estratégicas",
    "action_explanation": "Recupera tiempo de alto valor",
    "tool": "Regla 5/25",
    "tool_explanation": "Clasifica tareas por impacto real",
    "master_decision": "Gobierno del Tiempo",
    "master_decision_explanation": "Controlar agenda como activo estratégico",
    "master_action": "Diseñar agenda de alto rendimiento",
    "master_action_explanation": "Maximiza impacto del dueño",
    "master_tool": "Agenda Estratégica",
    "master_tool_explanation": "Sistema de gestión del tiempo"
  },
  {
    "code": "UCI-S5",
    "label": "Shock de Costes",
    "decision": "Estabilización de Costes",
    "decision_explanation": "Detectar costes fuera de control",
    "action": "Auditoría de gastos críticos",
    "action_explanation": "Reduce presión financiera",
    "tool": "Mapa de Costes Vitales",
    "tool_explanation": "Identifica costes que afectan supervivencia",
    "master_decision": "Gobierno de Costes",
    "master_decision_explanation": "Controlar estructura financiera",
    "master_action": "Diseñar estructura de costes óptima",
    "master_action_explanation": "Evita futuros shocks",
    "master_tool": "Arquitectura de Costes",
    "master_tool_explanation": "Modelo maestro de costes"
  },
  {
    "code": "UNI-S1",
    "label": "Esclerosis de Esperas",
    "decision": "Mapeo de Tiempos Muertos",
    "decision_explanation": "Identificar dónde se pierde tiempo entre pasos sin aportar valor",
    "action": "Cronometrar tiempos reales entre puestos",
    "action_explanation": "Hace visibles las esperas ocultas que encarecen el proceso",
    "tool": "Diagrama de Flujo de Valor",
    "tool_explanation": "Representa gráficamente el tiempo útil vs. el desperdicio",
    "master_decision": "Gobierno del Flujo",
    "master_decision_explanation": "El flujo se gobierna, no se observa pasivamente",
    "master_action": "Diseñar un sistema sin esperas estructurales",
    "master_action_explanation": "Convierte tiempo en capacidad productiva",
    "master_tool": "Radar de Flujo Operativo",
    "master_tool_explanation": "Visualiza bloqueos y fricciones del sistema"
  },
  {
    "code": "UNI-S2",
    "label": "Colapso de Agendas / Cuellos de Botella",
    "decision": "Priorización de Valor",
    "decision_explanation": "Enfocar la capacidad limitada en tareas que generan resultado",
    "action": "Eliminar tareas 'ruido' y proteger tiempo crítico",
    "action_explanation": "Reduce saturación directiva y desbloquea el flujo",
    "tool": "Regla 5/25 de Tareas + Planificador",
    "tool_explanation": "Clasifica tareas por impacto y urgencia real",
    "master_decision": "Dominio de la Capacidad",
    "master_decision_explanation": "La agenda refleja el poder real del negocio",
    "master_action": "Rediseñar prioridades según impacto sistémico",
    "master_action_explanation": "Libera capacidad estratégica",
    "master_tool": "Mapa de Capacidad Crítica",
    "master_tool_explanation": "Identifica cuellos que limitan todo el sistema"
  },
  {
    "code": "UNI-S3",
    "label": "Fugas de Calidad",
    "decision": "Estandarización Crítica",
    "decision_explanation": "Evitar errores repetidos por falta de criterios claros",
    "action": "Documentar fallos recurrentes y crear checklist de entrega",
    "action_explanation": "Reduce reprocesos y errores evitables",
    "tool": "Checklist de Calidad / Handoff",
    "tool_explanation": "Asegura continuidad y calidad entre áreas",
    "master_decision": "Diseño de la Ejecución",
    "master_decision_explanation": "La calidad se diseña, no se inspecciona",
    "master_action": "Crear estándares de salida innegociables",
    "master_action_explanation": "Elimina errores antes de producirse",
    "master_tool": "Arquitectura de Checkpoints",
    "master_tool_explanation": "Integra calidad en el proceso"
  },
  {
    "code": "UNI-S4",
    "label": "Micro-Fugas de Tiempo",
    "decision": "Eliminación de Desperdicio",
    "decision_explanation": "Suprimir pasos que no generan valor para el cliente",
    "action": "Eliminar actividades sin impacto directo",
    "action_explanation": "Reduce costes invisibles y acelera entregas",
    "tool": "Auditoría de Desperdicios (LEAN)",
    "tool_explanation": "Identifica desperdicio en tiempo, movimiento y espera",
    "master_decision": "Optimización del Flujo de Valor",
    "master_decision_explanation": "Cada paso debe justificar su existencia",
    "master_action": "Eliminar pasos sin retorno económico",
    "master_action_explanation": "Maximiza valor por unidad de tiempo",
    "master_tool": "Mapa de Valor Vivo",
    "master_tool_explanation": "Relaciona tiempo, coste y valor"
  },
  {
    "code": "UNI-S5",
    "label": "Obsolescencia de Método",
    "decision": "Actualización de Técnica",
    "decision_explanation": "Evitar que el 'siempre se hizo así' frene la mejora",
    "action": "Implementar una mejora semanal propuesta por el equipo",
    "action_explanation": "Activa mejora continua sin grandes proyectos",
    "tool": "Círculo de Mejora Continua",
    "tool_explanation": "Sistematiza pequeñas mejoras sostenidas",
    "master_decision": "Evolución Operativa",
    "master_decision_explanation": "El sistema aprende o se queda obsoleto",
    "master_action": "Institucionalizar mejora continua",
    "master_action_explanation": "Hace antifrágil la operación",
    "master_tool": "Sistema Kaizen Dirigido",
    "master_tool_explanation": "Canaliza mejoras alineadas al objetivo"
  },
  {
    "code": "UNI-S6",
    "label": "Despilfarro Operativo",
    "decision": "Eliminación de Grasa",
    "decision_explanation": "Reducir movimientos, esperas y exceso de inventario",
    "action": "Localizar desperdicios y ajustar reposición",
    "action_explanation": "Disminuye capital inmovilizado y fricción",
    "tool": "Registro de Mudas + Kanban",
    "tool_explanation": "Controla flujo y reposición según consumo real",
    "master_decision": "Activación de Recursos",
    "master_decision_explanation": "Los recursos deben trabajar o desaparecer",
    "master_action": "Convertir desperdicio en capacidad",
    "master_action_explanation": "Reduce coste estructural",
    "master_tool": "Tablero de Activación Lean",
    "master_tool_explanation": "Mide uso real de recursos"
  },
  {
    "code": "UNI-S7",
    "label": "Dependencia de Personas Clave",
    "decision": "Protocolización de Roles",
    "decision_explanation": "Reducir riesgo operativo ligado a individuos",
    "action": "Crear fichas de puesto con KPIs claros",
    "action_explanation": "Permite sustitución y escalabilidad",
    "tool": "Matriz de Polivalencia",
    "tool_explanation": "Mide capacidad de cubrir funciones críticas",
    "master_decision": "Soberanía del Rol",
    "master_decision_explanation": "El rol importa más que la persona",
    "master_action": "Diseñar puestos autónomos y replicables",
    "master_action_explanation": "El negocio no depende de héroes",
    "master_tool": "Arquitectura de Roles",
    "master_tool_explanation": "Separa función, responsabilidad y persona"
  },
  {
    "code": "UNI-S8",
    "label": "Ruido en la Comunicación",
    "decision": "Ritmos de Gestión",
    "decision_explanation": "Ordenar la toma de decisiones y la transmisión de órdenes",
    "action": "Implantar reuniones cortas y canales oficiales",
    "action_explanation": "Reduce errores por malentendidos",
    "tool": "Agenda de Gobierno Interno + Manual",
    "tool_explanation": "Estandariza cuándo, cómo y quién comunica",
    "master_decision": "Gobierno de la Decisión",
    "master_decision_explanation": "Decidir es un proceso, no un acto",
    "master_action": "Centralizar datos, ritmos y canales",
    "master_action_explanation": "Reduce errores estratégicos",
    "master_tool": "Sistema de Gobierno Interno",
    "master_tool_explanation": "Ordena información y autoridad"
  },
  {
    "code": "UNI-S9",
    "label": "Dependencia del Dueño",
    "decision": "Plan Preventivo Operativo",
    "decision_explanation": "Evitar paradas por descuido o improvisación",
    "action": "Establecer revisiones periódicas de activos clave",
    "action_explanation": "Reduce incidencias y dependencia personal",
    "tool": "Plan de Prevención",
    "tool_explanation": "Anticipa fallos antes de que ocurran",
    "master_decision": "Autonomía Sistémica",
    "master_decision_explanation": "El negocio debe operar sin presencia constante",
    "master_action": "Crear mecanismos de autocontrol",
    "master_action_explanation": "Libera tiempo del dueño",
    "master_tool": "Sistema de Autogestión",
    "master_tool_explanation": "Mantiene estabilidad sin supervisión directa"
  },
  {
    "code": "UNI-S10",
    "label": "Techo Operativo",
    "decision": "Ingeniería de Costes",
    "decision_explanation": "Detectar límites estructurales al crecimiento",
    "action": "Rediseñar procesos para reducir coste unitario",
    "action_explanation": "Permite crecer sin colapsar",
    "tool": "Mapa de Valorización S10 + RACI",
    "tool_explanation": "Relaciona coste, valor y responsabilidad",
    "master_decision": "Arquitectura Escalable",
    "master_decision_explanation": "El crecimiento se diseña antes de ejecutarse",
    "master_action": "Rediseñar procesos para crecer sin fricción",
    "master_action_explanation": "Permite escalar sin multiplicar problemas",
    "master_tool": "Arquitectura Operativa S10",
    "master_tool_explanation": "Define límites y palancas de escalado"
  },
  {
    "code": "CARDIO-S1",
    "label": "Arritmia de Ventas",
    "decision": "Radiografía de Cartera",
    "decision_explanation": "Detectar qué clientes generan ingresos reales y quiénes consumen recursos sin retorno",
    "action": "Clasificar clientes en Activos, Dormidos y Perdidos",
    "action_explanation": "Permite enfocar esfuerzos en clientes valiosos y reactivar los perdidos",
    "tool": "Clasificación de Clientes",
    "tool_explanation": "Visualiza el estado de cada cliente para priorizar acciones",
    "master_decision": "Gobierno de la Cartera",
    "master_decision_explanation": "Controlar flujo de clientes activos, inactivos y perdidos",
    "master_action": "Rediseñar segmentación y priorización de clientes",
    "master_action_explanation": "Convierte cartera en activo estratégico y reduce fugas",
    "master_tool": "Radar de Clientes Estratégicos",
    "master_tool_explanation": "Muestra estado y potencial de todos los clientes"
  },
  {
    "code": "CARDIO-S2",
    "label": "Fuga de Pacientes",
    "decision": "Protocolo de Rescate",
    "decision_explanation": "Evitar dependencia de un único cliente y minimizar riesgo de pérdida",
    "action": "Contactar clientes inactivos >90 días",
    "action_explanation": "Reduce riesgo de abandono y estabiliza ingresos",
    "tool": "Plan de Rescate Comercial",
    "tool_explanation": "Define pasos claros de intervención para clientes en riesgo",
    "master_decision": "Dominio del Riesgo",
    "master_decision_explanation": "Asegurar continuidad comercial sin depender de clientes individuales",
    "master_action": "Ejecutar plan de rescate inmediato y personalizado",
    "master_action_explanation": "Minimiza riesgo de pérdida y asegura ingresos",
    "master_tool": "Protocolo de Recuperación de Clientes",
    "master_tool_explanation": "Define acciones de retención y seguimiento crítico"
  },
  {
    "code": "CARDIO-S3",
    "label": "Oferta Confusa",
    "decision": "Inyección de Producto Estrella",
    "decision_explanation": "Aumentar claridad y relevancia de la oferta",
    "action": "Re-empaquetar producto de mayor margen como oferta principal",
    "action_explanation": "Mejora conversión y comprensión de valor",
    "tool": "Reposicionamiento de Producto",
    "tool_explanation": "Destaca la propuesta más rentable para el cliente",
    "master_decision": "Arquitectura de Producto",
    "master_decision_explanation": "Crear claridad absoluta sobre propuesta de valor",
    "master_action": "Reestructurar producto estrella y comunicación al cliente",
    "master_action_explanation": "Maximiza conversión y foco en margen",
    "master_tool": "Mapa de Valor Comercial",
    "master_tool_explanation": "Visualiza productos estratégicos y oportunidades"
  },
  {
    "code": "CARDIO-S4",
    "label": "Pipeline Obstruido",
    "decision": "Limpieza de Prospección",
    "decision_explanation": "Priorizar leads de alto potencial frente a contactos irrelevantes",
    "action": "Eliminar leads 'basura' y concentrarse en oportunidades reales",
    "action_explanation": "Reduce costes de adquisición y aumenta eficiencia",
    "tool": "Auditoría de Leads",
    "tool_explanation": "Clasifica prospectos según probabilidad de conversión",
    "master_decision": "Optimización de Prospección",
    "master_decision_explanation": "Convertir el pipeline en un motor de ingresos confiable",
    "master_action": "Repriorizar leads según potencial y ROI",
    "master_action_explanation": "Evita esfuerzos desperdiciados y acelera ventas",
    "master_tool": "Sistema de Leads Prioritarios",
    "master_tool_explanation": "Permite gestión dinámica de oportunidades valiosas"
  },
  {
    "code": "CARDIO-S5",
    "label": "Recurrencia Débil",
    "decision": "Plan de Fidelización",
    "decision_explanation": "Aumentar repetición de compra y hábito de consumo",
    "action": "Implementar ciclos de recompra automática o recordatorios",
    "action_explanation": "Incrementa ingresos recurrentes y relación con clientes",
    "tool": "Sistema de Fidelización",
    "tool_explanation": "Mantiene contacto constante y estructurado con clientes",
    "master_decision": "Diseño de Fidelización",
    "master_decision_explanation": "Convertir clientes en fuentes sostenibles de ingresos",
    "master_action": "Implementar ciclo automático de recompra y engagement",
    "master_action_explanation": "Genera hábito de compra y recurrencia",
    "master_tool": "Programa de Retención Estratégica",
    "master_tool_explanation": "Estandariza la relación con clientes a largo plazo"
  },
  {
    "code": "CARDIO-S6",
    "label": "Ticket Medio Bajo",
    "decision": "Estrategia de Upsell/Cross-sell",
    "decision_explanation": "Incrementar valor de cada cliente sin aumentar coste de adquisición",
    "action": "Diseñar ofertas complementarias para clientes actuales",
    "action_explanation": "Mejora margen por cliente y rentabilidad",
    "tool": "Paquetes y Bundles",
    "tool_explanation": "Permite combinar productos para aumentar ticket medio",
    "master_decision": "Maximización de Valor",
    "master_decision_explanation": "Aumentar rentabilidad por cliente sin esfuerzo adicional",
    "master_action": "Diseñar estrategias de upsell y cross-sell integradas",
    "master_action_explanation": "Incrementa margen global y ticket promedio",
    "master_tool": "Arquitectura de Ofertas Integradas",
    "master_tool_explanation": "Identifica combinaciones óptimas de venta"
  },
  {
    "code": "CARDIO-S7",
    "label": "Seguimiento Inexistente",
    "decision": "Automatización de Hitos",
    "decision_explanation": "Asegurar que cada venta recibe seguimiento sistemático",
    "action": "Configurar secuencias automáticas postventa",
    "action_explanation": "Evita pérdida de oportunidades y mejora experiencia del cliente",
    "tool": "CRM / Secuencias Automáticas",
    "tool_explanation": "Garantiza seguimiento consistente y documentado",
    "master_decision": "Control de Relación",
    "master_decision_explanation": "Garantizar que ninguna oportunidad se pierde",
    "master_action": "Automatizar y monitorizar hitos críticos de seguimiento",
    "master_action_explanation": "Asegura consistencia y cierre de oportunidades",
    "master_tool": "Plataforma CRM Estratégica",
    "master_tool_explanation": "Visualiza pipeline completo y acciones necesarias"
  },
  {
    "code": "CARDIO-S8",
    "label": "Dependencia de Canal",
    "decision": "Diversificación Comercial",
    "decision_explanation": "Reducir riesgo asociado a un único canal de ventas",
    "action": "Testar nuevos canales de captación",
    "action_explanation": "Aumenta resiliencia y oportunidades de ingreso",
    "tool": "Plan Multicanal",
    "tool_explanation": "Permite monitorizar desempeño y explorar nuevas fuentes",
    "master_decision": "Soberanía Comercial",
    "master_decision_explanation": "Reducir riesgo estructural de canal único",
    "master_action": "Testar y consolidar múltiples canales de captación",
    "master_action_explanation": "Diversifica ingresos y fortalece resiliencia",
    "master_tool": "Plan Multicanal Estratégico",
    "master_tool_explanation": "Mide efectividad de cada canal y prioriza inversión"
  },
  {
    "code": "CARDIO-S9",
    "label": "Mensaje Inefectivo",
    "decision": "Optimización de Conversión",
    "decision_explanation": "Aprender de cada 'no' y mejorar comunicación",
    "action": "Cambiar enfoque de 'lo que hago' a 'lo que resuelvo'",
    "action_explanation": "Incrementa efectividad comercial y conversión",
    "tool": "Revisión de Pitch Comercial",
    "tool_explanation": "Analiza resultados y ajusta mensajes estratégicamente",
    "master_decision": "Evolución del Pitch",
    "master_decision_explanation": "Transformar cada interacción en aprendizaje y conversión",
    "master_action": "Redefinir enfoque de comunicación hacia resolución de problemas",
    "master_action_explanation": "Mejora efectividad de cada contacto comercial",
    "master_tool": "Sistema de Optimización de Mensaje",
    "master_tool_explanation": "Permite ajustes continuos basados en resultados reales"
  },
  {
    "code": "CARDIO-S10",
    "label": "Venta Errática",
    "decision": "Optimización del LTV",
    "decision_explanation": "Incrementar fuerza comercial independiente del vendedor",
    "action": "Implementar sistema de lealtad y aumento de ticket medio",
    "action_explanation": "Aumenta ingresos recurrentes y retención de clientes",
    "tool": "Programa de Referidos y Loyalty",
    "tool_explanation": "Fomenta ventas adicionales y recomendación espontánea",
    "master_decision": "Marca Autónoma",
    "master_decision_explanation": "Hacer que la marca venda incluso sin presencia directa",
    "master_action": "Implementar lealtad, referidos y estrategias de aumento de ticket",
    "master_action_explanation": "Incrementa ingresos sostenibles y recurrentes",
    "master_tool": "Programa de Lealtad & Referral",
    "master_tool_explanation": "Sistema que amplifica ventas y fidelización sin intervención"
  },
  {
    "code": "NEURO-S1",
    "label": "Amnesia de Visión",
    "decision": "Fijación de Rumbo",
    "decision_explanation": "Detectar si el equipo conoce y entiende los objetivos estratégicos",
    "action": "Entrevista de alineación con el Comité",
    "action_explanation": "Alinea esfuerzos y elimina dispersión",
    "tool": "Manifiesto de Visión 1-Page",
    "tool_explanation": "Resume y comunica objetivos de manera clara y rápida",
    "master_decision": "Gobierno de la Visión",
    "master_decision_explanation": "Alinear mentalmente a todo el equipo con la dirección estratégica",
    "master_action": "Sistematizar revisión y comunicación de objetivos",
    "master_action_explanation": "Asegura que todos reman hacia el mismo Norte",
    "master_tool": "Manifiesto Estratégico",
    "master_tool_explanation": "Documento vivo de referencia para toda la organización"
  },
  {
    "code": "NEURO-S2",
    "label": "Dispersión de Foco",
    "decision": "Corte de Ramas",
    "decision_explanation": "Identificar proyectos que consumen tiempo sin impacto estratégico",
    "action": "Listar proyectos activos y filtrar por impacto",
    "action_explanation": "Permite al dueño centrarse en prioridades críticas",
    "tool": "Matriz de Priorización (Impacto/Esfuerzo)",
    "tool_explanation": "Clasifica iniciativas según valor y esfuerzo",
    "master_decision": "Dominio de Prioridades",
    "master_decision_explanation": "Reducir dispersión de tiempo y recursos en iniciativas de bajo impacto",
    "master_action": "Rediseñar portafolio de proyectos eliminando lastre",
    "master_action_explanation": "Optimiza concentración de esfuerzos y velocidad de ejecución",
    "master_tool": "Matriz de Impacto Estratégico",
    "master_tool_explanation": "Visualiza qué proyectos aportan verdadero valor"
  },
  {
    "code": "NEURO-S3",
    "label": "Improvisación",
    "decision": "Sincronización de Agenda",
    "decision_explanation": "Detectar productos o servicios que consumen recursos sin retorno",
    "action": "Definir 3 hitos innegociables del trimestre",
    "action_explanation": "Garantiza enfoque operativo y estratégico",
    "tool": "Roadmap Estratégico",
    "tool_explanation": "Visualiza metas clave y plazos de ejecución",
    "master_decision": "Arquitectura de Portafolio",
    "master_decision_explanation": "Evitar consumo de recursos en iniciativas sin retorno",
    "master_action": "Establecer hitos estratégicos trimestrales",
    "master_action_explanation": "Garantiza foco en resultados relevantes",
    "master_tool": "Roadmap Maestro",
    "master_tool_explanation": "Conecta estrategia con ejecución operativa"
  },
  {
    "code": "NEURO-S4",
    "label": "Intuición sin Datos",
    "decision": "Objetivación del Éxito",
    "decision_explanation": "Evitar decisiones basadas en corazonadas",
    "action": "Identificar 5 KPIs maestros a monitorear",
    "action_explanation": "Permite medir y actuar con datos",
    "tool": "Dashboard de Mando Neuro",
    "tool_explanation": "Visualiza indicadores clave y resultados estratégicos",
    "master_decision": "Gobierno por Indicadores",
    "master_decision_explanation": "Convertir intuición en decisiones basadas en datos",
    "master_action": "Seleccionar y monitorizar KPIs críticos",
    "master_action_explanation": "Permite decisiones rápidas y precisas",
    "master_tool": "Dashboard Estratégico",
    "master_tool_explanation": "Centraliza indicadores y muestra el estado del negocio"
  },
  {
    "code": "NEURO-S5",
    "label": "Fatiga Decisoria",
    "decision": "Protocolo de Decisión",
    "decision_explanation": "Reducir el agotamiento y aumentar velocidad de decisión",
    "action": "Implementar sistema de criterios para el 'SÍ'",
    "action_explanation": "Acelera decisiones y reduce indecisión",
    "tool": "Árbol de Decisión MASESORA",
    "tool_explanation": "Estandariza criterios y pasos de decisión",
    "master_decision": "Sistema de Decisión Ágil",
    "master_decision_explanation": "Estandarizar criterios y reducir indecisión",
    "master_action": "Definir protocolo de decisiones rápidas",
    "master_action_explanation": "Mejora velocidad y consistencia de decisiones",
    "master_tool": "Árbol de Decisión Avanzado",
    "master_tool_explanation": "Facilita aplicar criterios de juicio estratégicos"
  },
  {
    "code": "NEURO-S6",
    "label": "Silos Cognitivos",
    "decision": "Interconexión Departamental",
    "decision_explanation": "Detectar falta de comunicación entre áreas",
    "action": "Reunión de alineación cruzada (Cross-dept)",
    "action_explanation": "Conecta información y evita duplicidades",
    "tool": "Mapa de Dependencias",
    "tool_explanation": "Muestra relaciones y dependencias entre áreas",
    "master_decision": "Sinapsis Organizacional",
    "master_decision_explanation": "Integrar información entre departamentos y eliminar aislamiento",
    "master_action": "Implementar reuniones cross-dept y flujos de información",
    "master_action_explanation": "Mejora colaboración y eficiencia interdepartamental",
    "master_tool": "Mapa de Dependencias Estratégico",
    "master_tool_explanation": "Visualiza relaciones críticas y flujos de valor"
  },
  {
    "code": "NEURO-S7",
    "label": "Resistencia al Cambio",
    "decision": "Neuro-plasticidad",
    "decision_explanation": "Medir si la empresa depende del dueño o de sistemas replicables",
    "action": "Taller de gestión del cambio y nuevas metas",
    "action_explanation": "Facilita adopción de procesos y autonomía",
    "tool": "Plan de Adopción de Estrategia",
    "tool_explanation": "Acompaña transición hacia sistemas operativos autónomos",
    "master_decision": "Neuro-adaptabilidad",
    "master_decision_explanation": "La empresa debe adaptarse sin depender de líderes individuales",
    "master_action": "Talleres de cambio y adopción de nuevas metas",
    "master_action_explanation": "Facilita resiliencia organizacional",
    "master_tool": "Plan de Adopción Estratégico",
    "master_tool_explanation": "Sistematiza cambio cultural y operativo"
  },
  {
    "code": "NEURO-S8",
    "label": "Incoherencia Táctica",
    "decision": "Alineación Vertical",
    "decision_explanation": "Medir si los objetivos se traducen en acciones consistentes",
    "action": "Revisar que tareas del equipo sumen a los KPIs",
    "action_explanation": "Garantiza que cada acción aporta al objetivo",
    "tool": "Cascada de Objetivos (OKR)",
    "tool_explanation": "Conecta visión estratégica con ejecución diaria",
    "master_decision": "Alineación de Ejecución",
    "master_decision_explanation": "Garantizar que estrategia se traduzca en acción consistente",
    "master_action": "Revisar tareas y KPIs alineados a objetivos estratégicos",
    "master_action_explanation": "Minimiza errores tácticos y dispersión",
    "master_tool": "Cascada OKR Avanzada",
    "master_tool_explanation": "Conecta objetivos estratégicos con resultados operativos"
  },
    {
    "code": "NEURO-S9",
    "label": "Cortoplacismo",
    "decision": "Visión Prospectiva",
    "decision_explanation": "Detectar vulnerabilidades frente a competencia",
    "action": "Sesión de análisis de amenazas y oportunidades",
    "action_explanation": "Fortalece diferenciación y blindaje del negocio",
    "tool": "Matriz DAFO Dinámica",
    "tool_explanation": "Identifica ventajas competitivas y riesgos emergentes",
    "master_decision": "Visión Prospectiva Estratégica",
    "master_decision_explanation": "Mantener ventaja competitiva y barreras de entrada",
    "master_action": "Sesión de análisis prospectivo y escenarios futuros",
    "master_action_explanation": "Protege márgenes y fortalece posición",
    "master_tool": "Matriz DAFO Dinámica Avanzada",
    "master_tool_explanation": "Analiza amenazas, oportunidades y ventajas sostenibles"
  },
  {
    "code": "NEURO-S10",
    "label": "Cerebro Alineado",
    "decision": "Sello de Alta Neurológica",
    "decision_explanation": "Medir el valor de la estrategia respecto a la inversión del dueño",
    "action": "Evaluación de alineación del 100% del equipo",
    "action_explanation": "Permite que el negocio sea un activo financiero independiente",
    "tool": "Certificado de Foco Estratégico",
    "tool_explanation": "Certifica alineación, claridad y madurez estratégica",
    "master_decision": "Sello de Maestría Estratégica",
    "master_decision_explanation": "Transformar la empresa en un activo autónomo y escalable",
    "master_action": "Certificar alineación y claridad total de objetivos y equipo",
    "master_action_explanation": "Convierte estrategia en patrimonio empresarial",
    "master_tool": "Certificado de Gobierno Estratégico",
    "master_tool_explanation": "Garantiza que visión, ejecución y resultados están totalmente conectados"
  },
  {
    "code": "CLI-S1",
    "label": "Infarto por Urgencias",
    "decision": "Drenaje de Incendios",
    "decision_explanation": "Detectar retrasos en cierre y decisiones basadas en intuición",
    "action": "Clasificar tareas diarias en Operar vs. Gestionar",
    "action_explanation": "Evita apagar fuegos y prioriza acciones críticas",
    "tool": "Matriz Operar/Gestionar",
    "tool_explanation": "Permite identificar actividades de alto impacto vs. rutina",
    "master_decision": "Gobierno de Emergencias",
    "master_decision_explanation": "El negocio debe reaccionar rápido sin caos",
    "master_action": "Implementar flujo de decisiones críticas automáticas",
    "master_action_explanation": "Reduce latencia y errores en cierre financiero",
    "master_tool": "Flujo de Drenaje Estratégico",
    "master_tool_explanation": "Coordina acciones de urgencia sin intervención manual"
  },
  {
    "code": "CLI-S2",
    "label": "Esclerosis Documental",
    "decision": "Fluidez de Información",
    "decision_explanation": "Medir si los datos realmente permiten actuar",
    "action": "Organizar el 'Cerebro Digital' (nube unificada)",
    "action_explanation": "Centraliza información y reduce burocracia",
    "tool": "Repositorio Digital Unificado",
    "tool_explanation": "Facilita búsqueda, acceso y control de información",
    "master_decision": "Control de Información",
    "master_decision_explanation": "Transformar datos dispersos en conocimiento accionable",
    "master_action": "Centralizar y etiquetar información clave",
    "master_action_explanation": "Facilita decisiones rápidas y precisas",
    "master_tool": "Cerebro Digital Integrado",
    "master_tool_explanation": "Muestra la información relevante organizada y accesible"
  },
  {
    "code": "CLI-S3",
    "label": "Atrofia de Tiempos",
    "decision": "Recuperación de Autonomía",
    "decision_explanation": "Identificar tareas que consumen tiempo innecesario",
    "action": "Detectar el 20% de tareas que roban el 80% del tiempo",
    "action_explanation": "Libera tiempo para tareas estratégicas",
    "tool": "Hoja de Registro de Tiempo",
    "tool_explanation": "Visualiza dónde se pierde tiempo y permite optimización",
    "master_decision": "Optimización de Actividades",
    "master_decision_explanation": "Cada minuto debe generar valor real",
    "master_action": "Automatizar y eliminar tareas de bajo impacto",
    "master_action_explanation": "Incrementa productividad y eficiencia del equipo",
    "master_tool": "Analizador de Tiempos Críticos",
    "master_tool_explanation": "Detecta cuellos de botella y optimiza flujos"
  },
  {
    "code": "CLI-S4",
    "label": "Memoria Volátil",
    "decision": "Fijación de Conocimiento",
    "decision_explanation": "Evitar dependencia de la memoria humana",
    "action": "Protocolizar las 5 acciones que más errores generan",
    "action_explanation": "Reduce errores y asegura continuidad operativa",
    "tool": "Procedimientos Estandarizados",
    "tool_explanation": "Documenta conocimiento crítico y reduce riesgo humano",
    "master_decision": "Gobernanza del Conocimiento",
    "master_decision_explanation": "Transformar conocimiento tácito en patrimonio operativo",
    "master_action": "Protocolizar y documentar procesos críticos",
    "master_action_explanation": "Evita pérdida de información y dependencia de personas",
    "master_tool": "Sistema de Procedimientos Inteligente",
    "master_tool_explanation": "Actualiza y comunica procesos automáticamente"
  },
  {
    "code": "CLI-S5",
    "label": "Músculo Agotado",
    "decision": "Sustitución Mecánica",
    "decision_explanation": "Detectar procesos manuales que consumen recursos",
    "action": "Sustituir 1 proceso manual por flujo automático",
    "action_explanation": "Incrementa eficiencia y libera al equipo",
    "tool": "Automatización de Procesos",
    "tool_explanation": "Convierte tareas repetitivas en procesos automáticos",
    "master_decision": "Flujo Automático",
    "master_decision_explanation": "Convertir tareas repetitivas en procesos que se autoejecutan",
    "master_action": "Implementar automatizaciones clave",
    "master_action_explanation": "Libera recursos y acelera ejecución",
    "master_tool": "Plataforma de Automatización",
    "master_tool_explanation": "Garantiza ejecución consistente sin intervención manual"
  },
  {
    "code": "CLI-S6",
    "label": "Parálisis por Análisis",
    "decision": "Simplificación de Mando",
    "decision_explanation": "Evitar que exceso de información bloquee decisiones",
    "action": "Reducir datos a 3 KPIs críticos",
    "action_explanation": "Permite enfoque en indicadores que realmente importan",
    "tool": "Panel de Control Ejecutivo",
    "tool_explanation": "Facilita decisiones rápidas con información clave",
    "master_decision": "Decisión Ágil",
    "master_decision_explanation": "Reducir complejidad informativa para tomar decisiones estratégicas",
    "master_action": "Filtrar información a KPIs críticos",
    "master_action_explanation": "Mejora velocidad y precisión de decisiones",
    "master_tool": "Dashboard Estratégico",
    "master_tool_explanation": "Presenta indicadores estratégicos en tiempo real"
  },
  {
    "code": "CLI-S7",
    "label": "Dependencia de Órganos",
    "decision": "Descentralización",
    "decision_explanation": "Evitar que el dueño controle cada acción",
    "action": "Crear sistema de reporte autónomo del dueño",
    "action_explanation": "Da claridad de responsabilidades y autonomía",
    "tool": "Sistema de Reporte Automático",
    "tool_explanation": "Permite control sin intervención directa",
    "master_decision": "Autonomía Sistémica",
    "master_decision_explanation": "Hacer que el sistema funcione sin dueño",
    "master_action": "Crear reportes y alertas automáticas",
    "master_action_explanation": "Permite operación sin supervisión constante",
    "master_tool": "Sistema de Reporte Autónomo",
    "master_tool_explanation": "Facilita control y seguimiento independiente"
  },
  {
    "code": "CLI-S8",
    "label": "Fricción de Engranajes",
    "decision": "Integración de Flujos",
    "decision_explanation": "Detectar duplicación y esfuerzos manuales",
    "action": "Conectar herramientas y procesos",
    "action_explanation": "Reduce trabajo manual y errores de transferencia",
    "tool": "Integración de Sistemas",
    "tool_explanation": "Garantiza datos únicos y procesos coordinados",
    "master_decision": "Sincronización de Sistemas",
    "master_decision_explanation": "Eliminar fricción entre herramientas y procesos",
    "master_action": "Integrar plataformas y datos",
    "master_action_explanation": "Aumenta eficiencia y reduce errores",
    "master_tool": "Hub de Integración Operativa",
    "master_tool_explanation": "Garantiza coordinación total de procesos digitales"
  },
  {
    "code": "CLI-S9",
    "label": "Rigidez Estructural",
    "decision": "Elasticidad Operativa",
    "decision_explanation": "Medir capacidad de previsión y reacción",
    "action": "Crear plan de 'crecimiento sin estrés'",
    "action_explanation": "Permite escalar operaciones sin colapsar",
    "tool": "Plan de Escalabilidad Operativa",
    "tool_explanation": "Alinea recursos y procesos con crecimiento proyectado",
    "master_decision": "Escalabilidad Controlada",
    "master_decision_explanation": "Preparar la empresa para crecer sin fricciones",
    "master_action": "Diseñar plan de escalabilidad operativa",
    "master_action_explanation": "Permite crecimiento sostenible y seguro",
    "master_tool": "Plan Maestro de Escalabilidad",
    "master_tool_explanation": "Coordina recursos, procesos y equipos con proyección"
  },
  {
    "code": "CLI-S10",
    "label": "Dependencia",
    "decision": "Simulacro de Autonomía",
    "decision_explanation": "Evaluar si los departamentos pueden operar sin supervisión constante",
    "action": "Superar 7 días de operativa sin intervención del dueño",
    "action_explanation": "Verifica madurez operativa y confianza",
    "tool": "Prueba de Autonomía Operativa",
    "tool_explanation": "Comprueba capacidad de operación independiente",
    "master_decision": "Sello de Autonomía Operativa",
    "master_decision_explanation": "Certificar que la empresa puede operar sin intervención",
    "master_action": "Ejecutar simulaciones de operación autónoma",
    "master_action_explanation": "Evalúa madurez operativa y capacidad de auto-sostenimiento",
    "master_tool": "Certificado de Operatividad Independiente",
    "master_tool_explanation": "Verifica autonomía completa del sistema"
  },
  {
    "code": "CIR-S1",
    "label": "Imagen no óptima",
    "decision": "Radiografía Estética",
    "decision_explanation": "Detectar deficiencias visuales y físicas de la marca",
    "action": "Auditoría visual 360º de identidad y local",
    "action_explanation": "Identifica puntos críticos y áreas de mejora",
    "tool": "Informe Puntos Críticos",
    "tool_explanation": "Documenta estado actual de la marca y entorno físico",
    "master_decision": "Gobierno Estético",
    "master_decision_explanation": "Transformar percepción visual de manera inmediata",
    "master_action": "Auditoría completa de identidad y local",
    "master_action_explanation": "Identifica todas las oportunidades de impacto",
    "master_tool": "Informe de Estado de Marca",
    "master_tool_explanation": "Diagnóstico visual estratégico"
  },
  {
    "code": "CIR-S2",
    "label": "Local sin Identidad",
    "decision": "Ajuste de Entorno",
    "decision_explanation": "Evitar que la experiencia local contradiga la marca digital",
    "action": "Cambiar iluminación, orden y señalética",
    "action_explanation": "Alinea experiencia presencial con percepción de marca",
    "tool": "Checklist de Puesta a Punto",
    "tool_explanation": "Lista de mejoras visuales rápidas y medibles",
    "master_decision": "Coherencia Experiencial",
    "master_decision_explanation": "Integrar todos los puntos de contacto",
    "master_action": "Rediseño de iluminación, orden y señalética",
    "master_action_explanation": "Garantiza uniformidad de la marca",
    "master_tool": "Checklist de Coherencia",
    "master_tool_explanation": "Lista de verificación para consistencia visual"
  },
  {
    "code": "CIR-S3",
    "label": "Bienvenida Fría",
    "decision": "Detalle de Recepción",
    "decision_explanation": "El primer contacto genera percepción inmediata de la marca",
    "action": "Implementar café, aroma o saludo especial",
    "action_explanation": "Mejora primera impresión y sensación de cuidado",
    "tool": "Manual de Primera Impresión",
    "tool_explanation": "Establece protocolos de bienvenida consistentes",
    "master_decision": "Experiencia WOW",
    "master_decision_explanation": "Convertir la recepción en un impacto memorable",
    "master_action": "Protocolos de bienvenida multisensorial",
    "master_action_explanation": "Genera primera impresión positiva e inolvidable",
    "master_tool": "Manual de Primera Impresión Avanzado",
    "master_tool_explanation": "Estándar de interacción inicial con clientes"
  },
  {
    "code": "CIR-S4",
    "label": "Puntos de Dolor",
    "decision": "Ergonomía de Servicio",
    "decision_explanation": "Identificar fricciones en la experiencia del cliente",
    "action": "Eliminación de fricciones en atención y venta",
    "action_explanation": "Facilita el proceso y aumenta tiempo de exposición a la oferta",
    "tool": "Checklist Fricción Cero",
    "tool_explanation": "Lista de pasos críticos de atención optimizados",
    "master_decision": "Servicio Sin Fricción",
    "master_decision_explanation": "Eliminar fricciones que reducen conversión y satisfacción",
    "master_action": "Rediseño completo del flujo de atención",
    "master_action_explanation": "Mejora percepción y experiencia de compra",
    "master_tool": "Checklist de Experiencia Perfecta",
    "master_tool_explanation": "Estándares para atención fluida y agradable"
  },
  {
    "code": "CIR-S5",
    "label": "Falta de Cariño",
    "decision": "Micro-experiencias",
    "decision_explanation": "Detectar falta de conexión emocional con el cliente",
    "action": "Añadir nota escrita o detalle tras compra",
    "action_explanation": "Genera vínculo y fidelización",
    "tool": "Lista de Acciones WOW",
    "tool_explanation": "Registro de micro-impactos para clientes",
    "master_decision": "Micro-Conexión",
    "master_decision_explanation": "Crear vínculo emocional con cada cliente",
    "master_action": "Implementar micro-experiencias personalizadas",
    "master_action_explanation": "Aumenta fidelización y engagement",
    "master_tool": "Plan de Acciones WOW",
    "master_tool_explanation": "Registro y seguimiento de experiencias de alto impacto"
  },
  {
    "code": "CIR-S6",
    "label": "Propuestas Visuales de Stock",
    "decision": "Humanización Exprés",
    "decision_explanation": "Evitar marca fría y genérica",
    "action": "Hacer fotos reales del equipo y productos estrella",
    "action_explanation": "Comunica autenticidad y cercanía",
    "tool": "Protocolo de Presentación / Banco de Imágenes",
    "tool_explanation": "Establece estándar de presentación visual coherente",
    "master_decision": "Humanización de Marca",
    "master_decision_explanation": "Convertir la marca en algo cercano y confiable",
    "master_action": "Fotos reales y storytelling visual del equipo",
    "master_action_explanation": "Mejora confianza y cercanía",
    "master_tool": "Banco de Imágenes Estratégico",
    "master_tool_explanation": "Estandariza la comunicación visual auténtica"
  },
  {
    "code": "CIR-S7",
    "label": "Amnesia Post-Venta",
    "decision": "Sistema de Fidelización",
    "decision_explanation": "Evitar pérdida de clientes tras la compra",
    "action": "Crear programa de retención y contacto",
    "action_explanation": "Mantiene relación y asegura recompra",
    "tool": "Plan de Retención",
    "tool_explanation": "Sistema estructurado de seguimiento post-venta",
    "master_decision": "Retención Inteligente",
    "master_decision_explanation": "Garantizar que la relación continúe tras la venta",
    "master_action": "Sistema de seguimiento y recompra automática",
    "master_action_explanation": "Evita pérdida de clientes y maximiza LTV",
    "master_tool": "Plan Maestro de Retención",
    "master_tool_explanation": "Sistema integral de fidelización multicanal"
  },
  {
    "code": "CIR-S8",
    "label": "Falta de Rasgos",
    "decision": "Diferenciación Única",
    "decision_explanation": "Evitar que la marca sea copiable o irrelevante",
    "action": "Definir propuesta de valor única",
    "action_explanation": "Protege margen y marca frente a competencia",
    "tool": "Matriz de Atributos Críticos",
    "tool_explanation": "Identifica los elementos diferenciadores clave",
    "master_decision": "Diferenciación Estratégica",
    "master_decision_explanation": "Convertir la marca en un activo único",
    "master_action": "Definir atributos distintivos y defensibles",
    "master_action_explanation": "Protege margen y reconocimiento",
    "master_tool": "Matriz de Diferenciación Premium",
    "master_tool_explanation": "Identifica elementos de alto valor percibido"
  },
  {
    "code": "CIR-S9",
    "label": "Captación Dormida",
    "decision": "Impulso de Atracción",
    "decision_explanation": "Detectar clientes no comprometidos que podrían generar valor",
    "action": "Lanzar promoción visualmente potente",
    "action_explanation": "Aumenta visibilidad y tráfico cualificado",
    "tool": "Campaña Flash de Atracción",
    "tool_explanation": "Acciones rápidas y medibles de impacto comercial",
    "master_decision": "Atracción Proactiva",
    "master_decision_explanation": "Detectar y activar clientes potenciales de alto valor",
    "master_action": "Campaña de visibilidad intensa y segmentada",
    "master_action_explanation": "Genera tráfico cualificado y rápido impacto",
    "master_tool": "Flash Campaign Planner",
    "master_tool_explanation": "Herramienta de ejecución de campañas de efecto inmediato"
  },
    {
    "code": "CIR-S10",
    "label": "Belleza Integral / Cicatrices de Marca",
    "decision": "Sello de Alta Evolutiva",
    "decision_explanation": "Evaluar fuerza de la marca y reputación",
    "action": "Medición de NPS y monitorizar reseñas",
    "action_explanation": "Permite crecimiento orgánico sostenible",
    "tool": "Informe de Valor de Marca S10",
    "tool_explanation": "Certifica excelencia externa y reputación positiva",
    "master_decision": "Sello de Excelencia",
    "master_decision_explanation": "Evaluar y certificar reputación y percepción",
    "master_action": "Medición de NPS, reseñas y reputación online",
    "master_action_explanation": "Permite crecimiento orgánico sostenible y reforzar marca",
    "master_tool": "Informe de Reputación Estratégica",
    "master_tool_explanation": "Certifica percepción positiva y consistencia de marca"
  },
  {
    "code": "PSI-S1",
    "label": "Neurosis Operativa",
    "decision": "Desbloqueo Mental",
    "decision_explanation": "Identificar frenos mentales que bloquean productividad",
    "action": "Detectar los 3 frenos más comunes en el equipo",
    "action_explanation": "Elimina hábitos improductivos y acelera flujo de trabajo",
    "tool": "Cuestionario de Creencias Limitantes",
    "tool_explanation": "Evalúa patrones de pensamiento que generan bloqueo",
    "master_decision": "Reprogramación Cognitiva",
    "master_decision_explanation": "Rediseñar hábitos mentales que frenan productividad",
    "master_action": "Diagnóstico de bloqueos y reentrenamiento",
    "master_action_explanation": "Elimina patrones improductivos a nivel profundo",
    "master_tool": "Cuestionario Avanzado de Creencias",
    "master_tool_explanation": "Herramienta de diagnóstico psicológico y conductual"
  },
  {
    "code": "PSI-S2",
    "label": "Conflicto de Perfiles",
    "decision": "Sincronización DISC",
    "decision_explanation": "Asignar roles según fortalezas individuales",
    "action": "Test de perfil conductual en puestos clave",
    "action_explanation": "Potencia talento natural y reduce conflictos",
    "tool": "Matriz de Perfiles DISC",
    "tool_explanation": "Muestra la alineación entre persona y puesto",
    "master_decision": "Optimización de Roles",
    "master_decision_explanation": "Maximizar rendimiento asignando roles según talento",
    "master_action": "Reasignación estratégica basada en perfiles DISC",
    "master_action_explanation": "Aumenta eficacia y reduce fricción",
    "master_tool": "Matriz Estratégica DISC",
    "master_tool_explanation": "Visualiza la compatibilidad rol-persona"
  },
  {
    "code": "PSI-S3",
    "label": "Anhedonia Laboral",
    "decision": "Activación del Dopamina",
    "decision_explanation": "Recuperar motivación intrínseca del equipo",
    "action": "Crear sistema de 'Quick Wins'",
    "action_explanation": "Refuerza logros y engagement",
    "tool": "Plan de Reconocimiento Inmediato",
    "tool_explanation": "Protocoliza recompensas rápidas y visibles",
    "master_decision": "Motivación Sostenible",
    "master_decision_explanation": "Activar motivación intrínseca permanente",
    "master_action": "Sistema de recompensas y logros visibles",
    "master_action_explanation": "Incrementa compromiso y retención",
    "master_tool": "Plan Maestro de Reconocimiento",
    "master_tool_explanation": "Estandariza reconocimiento continuo"
  },
  {
    "code": "PSI-S4",
    "label": "Liderazgo Bipolar",
    "decision": "Coherencia de Mando",
    "decision_explanation": "Alinear mensajes y acciones de liderazgo",
    "action": "Auditoría de contradicciones en cadena de mando",
    "action_explanation": "Evita mensajes contradictorios y mejora claridad",
    "tool": "Test de Coherencia de Liderazgo",
    "tool_explanation": "Diagnóstico de consistencia en liderazgo",
    "master_decision": "Gobernanza del Mando",
    "master_decision_explanation": "Asegurar coherencia y predictibilidad del liderazgo",
    "master_action": "Protocolizar comunicación y decisiones",
    "master_action_explanation": "Reduce incertidumbre y mejora alineación",
    "master_tool": "Dashboard de Liderazgo",
    "master_tool_explanation": "Monitoriza consistencia y decisiones de líderes"
  },
  {
    "code": "PSI-S5",
    "label": "Estrés Post-Crisis",
    "decision": "Resiliencia Organizativa",
    "decision_explanation": "Restaurar energía tras situaciones críticas",
    "action": "Sesiones de ventilación y enfoque a futuro",
    "action_explanation": "Reduce estrés y evita rotación voluntaria",
    "tool": "Protocolo de Gestión de Crisis Emocional",
    "tool_explanation": "Guía para recuperación rápida del equipo",
    "master_decision": "Recuperación Activa",
    "master_decision_explanation": "Restaurar resiliencia del equipo",
    "master_action": "Implementación de sesiones estructuradas post-crisis",
    "master_action_explanation": "Minimiza impacto emocional y operativo",
    "master_tool": "Protocolo Integral de Crisis",
    "master_tool_explanation": "Plan de acción para recuperación emocional"
  },
  {
    "code": "PSI-S6",
    "label": "Valores Fantasma",
    "decision": "Encarnación de Cultura",
    "decision_explanation": "Hacer tangibles los valores de la empresa",
    "action": "Traducir valores en 3 conductas prohibidas y 3 premiadas",
    "action_explanation": "Refuerza cultura deseada y conducta correcta",
    "tool": "Código de Conducta Consciente",
    "tool_explanation": "Manual de valores aplicado al día a día",
    "master_decision": "Cultura Tangible",
    "master_decision_explanation": "Convertir valores en acciones observables",
    "master_action": "Integración de valores en KPI y conducta",
    "master_action_explanation": "Facilita adopción y seguimiento",
    "master_tool": "Código de Conducta Estratégico",
    "master_tool_explanation": "Transformación de valores en práctica diaria"
  },
  {
    "code": "PSI-S7",
    "label": "Comunicación Pasivo-Agresiva",
    "decision": "Asertividad Radical",
    "decision_explanation": "Hablar claro sin generar conflictos",
    "action": "Formación en comunicación no violenta y feedback directo",
    "action_explanation": "Mejora interacción y reduce frustración",
    "tool": "Guía de Feedback MASESORA",
    "tool_explanation": "Herramienta para conversaciones difíciles",
    "master_decision": "Claridad Radical",
    "master_decision_explanation": "Mejorar comunicación interna efectiva",
    "master_action": "Talleres y simulaciones de feedback",
    "master_action_explanation": "Eleva nivel de interacción y reduce malentendidos",
    "master_tool": "Kit de Comunicación Efectiva",
    "master_tool_explanation": "Herramienta de entrenamiento y seguimiento"
  },
  {
    "code": "PSI-S8",
    "label": "Fuga de Sentido",
    "decision": "Propósito Conectado",
    "decision_explanation": "Vincular objetivos personales con empresariales",
    "action": "Taller de alineación de propósito",
    "action_explanation": "Incrementa sentido de pertenencia y motivación",
    "tool": "Manifiesto del Propósito",
    "tool_explanation": "Documento de referencia de propósito alineado",
    "master_decision": "Propósito Compartido",
    "master_decision_explanation": "Alinear propósito personal con el empresarial",
    "master_action": "Taller de alineación estratégica",
    "master_action_explanation": "Incrementa engagement y motivación",
    "master_tool": "Manifiesto de Propósito Estratégico",
    "master_tool_explanation": "Documento maestro de alineación cultural"
  },
  {
    "code": "PSI-S9",
    "label": "Egos Inflamados",
    "decision": "Humildad Organizativa",
    "decision_explanation": "Fomentar colaboración real",
    "action": "Implementar proyectos transversales",
    "action_explanation": "Elimina competencia interna y promueve cooperación",
    "tool": "Matriz de Colaboración Cruzada",
    "tool_explanation": "Herramienta para visualizar y medir sinergias",
    "master_decision": "Sinergia Organizacional",
    "master_decision_explanation": "Promover colaboración y eliminar reinos de taifas",
    "master_action": "Proyectos interdepartamentales con objetivos claros",
    "master_action_explanation": "Fortalece colaboración y eficiencia",
    "master_tool": "Matriz de Colaboración Estratégica",
    "master_tool_explanation": "Visualiza impacto y resultados de sinergias"
  },
  {
    "code": "PSI-S10",
    "label": "Paz del Recibo",
    "decision": "Alineación de Talento",
    "decision_explanation": "Que cada rol tenga energía y claridad",
    "action": "Vincular perfil psicológico con responsabilidad",
    "action_explanation": "Optimiza asignación y reduce desgaste",
    "tool": "Manifiesto del Propósito S10",
    "tool_explanation": "Estándar de alineación de energía, propósito y rol",
    "master_decision": "Vitalidad Estratégica",
    "master_decision_explanation": "Mantener niveles óptimos de energía y compromiso",
    "master_action": "Vinculación de energía, propósito y rol",
    "master_action_explanation": "Garantiza sostenibilidad y desempeño alto",
    "master_tool": "Dashboard de Talento y Propósito",
    "master_tool_explanation": "Herramienta para seguimiento integral de energía y motivación"
  },
  {
    "code": "RES-S1",
    "label": "Fuga de Talento",
    "decision": "Blindaje de Clave",
    "decision_explanation": "Retener a empleados que realmente suman",
    "action": "Entrevistas de fidelización con perfiles A",
    "action_explanation": "Asegura continuidad de conocimiento crítico y alto desempeño",
    "tool": "Mapa de Talento (Matriz 9-Box)",
    "tool_explanation": "Visualiza talento vs. potencial para priorizar retención",
    "master_decision": "Retención Estratégica",
    "master_decision_explanation": "Mantener los A-Players críticos",
    "master_action": "Estrategia de fidelización personalizada",
    "master_action_explanation": "Garantiza continuidad y crecimiento sostenido",
    "master_tool": "Mapa Estratégico de Talento 9-Box",
    "master_tool_explanation": "Prioriza recursos y esfuerzos de retención"
  },
  {
    "code": "RES-S2",
    "label": "Baja Productividad",
    "decision": "Alineación de Objetivos",
    "decision_explanation": "Que cada puesto tenga metas claras y medibles",
    "action": "Definir 3 objetivos clave por puesto",
    "action_explanation": "Reduce tiempo perdido y acelera curva de adaptación",
    "tool": "Cuadro de Mandos Operativo",
    "tool_explanation": "Herramienta de seguimiento de objetivos individuales",
    "master_decision": "Optimización de Rol",
    "master_decision_explanation": "Cada persona contribuye al máximo",
    "master_action": "KPI claros + objetivos alineados",
    "master_action_explanation": "Aumenta impacto de cada rol y reduce sobrecarga",
    "master_tool": "Dashboard de Desempeño Individual",
    "master_tool_explanation": "Visualiza contribución y progreso"
  },
  {
    "code": "RES-S3",
    "label": "Clima Tóxico",
    "decision": "Saneamiento Cultural",
    "decision_explanation": "Cortar comportamientos negativos antes de que se propaguen",
    "action": "Encuesta de clima rápida y anónima",
    "action_explanation": "Detecta focos de conflicto y permite acción inmediata",
    "tool": "eNPS (Employee NPS)",
    "tool_explanation": "Mide compromiso y satisfacción del equipo",
    "master_decision": "Cultura Regenerativa",
    "master_decision_explanation": "Mejorar engagement y cohesión",
    "master_action": "Acciones inmediatas de ajuste cultural",
    "master_action_explanation": "Reduce rotación y conflictos",
    "master_tool": "eNPS Avanzado + Feedback Continuo",
    "master_tool_explanation": "Mide evolución y compromiso en tiempo real"
  },
  {
    "code": "RES-S4",
    "label": "Liderazgo Ausente",
    "decision": "Escuela de Mandos",
    "decision_explanation": "Enseñar a delegar sin perder control",
    "action": "Formación en comunicación y reporte",
    "action_explanation": "Reduce interrupciones al dueño y empodera mandos intermedios",
    "tool": "Protocolo de Delegación",
    "tool_explanation": "Guía para delegar tareas manteniendo accountability",
    "master_decision": "Delegación Inteligente",
    "master_decision_explanation": "Empoderar mandos sin perder control",
    "master_action": "Formación en reporting y comunicación estratégica",
    "master_action_explanation": "Optimiza tiempo del dueño y fortalece mandos intermedios",
    "master_tool": "Protocolo Dinámico de Delegación",
    "master_tool_explanation": "Permite seguimiento y control remoto de tareas"
  },
  {
    "code": "RES-S5",
    "label": "Selección Fallida",
    "decision": "Protocolo de Fichaje",
    "decision_explanation": "Contratar con criterio y no por urgencia",
    "action": "Definir 'Avatar de Empleado Ideal'",
    "action_explanation": "Evita reincidencia de malos fichajes y fortalece cultura",
    "tool": "Scorecard de Reclutamiento",
    "tool_explanation": "Evaluación estructurada de candidatos según perfil y potencial",
    "master_decision": "Reclutamiento de Alto Impacto",
    "master_decision_explanation": "Contratar para escalar",
    "master_action": "Definir perfil ideal + pruebas prácticas",
    "master_action_explanation": "Reduce riesgo de malos fichajes y fortalece cultura",
    "master_tool": "Scorecard Predictivo",
    "master_tool_explanation": "Priorización de candidatos según impacto esperado"
  },
  {
    "code": "RES-S6",
    "label": "Caos Retributivo",
    "decision": "Equidad Salarial",
    "decision_explanation": "Ajustar incentivos a resultados y roles",
    "action": "Diseño de bonus vinculados a resultados",
    "action_explanation": "Alinea motivación con desempeño y reduce frustración",
    "tool": "Plan de Incentivos",
    "tool_explanation": "Estructura de compensación vinculada a KPIs y objetivos",
    "master_decision": "Incentivos Estratégicos",
    "master_decision_explanation": "Vincular rendimiento y compensación",
    "master_action": "Bonus ligados a resultados + objetivos estratégicos",
    "master_action_explanation": "Alinea motivación con KPIs y estrategia de empresa",
    "master_tool": "Plan Maestro de Incentivos",
    "master_tool_explanation": "Seguimiento y ajuste en tiempo real según desempeño"
  },
  {
    "code": "RES-S7",
    "label": "Desconocimiento",
    "decision": "Plan de Formación",
    "decision_explanation": "Evitar obsolescencia del equipo",
    "action": "Detección de necesidades técnicas y formación continua",
    "action_explanation": "Mejora habilidades y permite adaptación constante",
    "tool": "Matriz de Capacitación",
    "tool_explanation": "Herramienta de seguimiento y planificación de desarrollo",
    "master_decision": "Formación Continua",
    "master_decision_explanation": "Mantener habilidades actualizadas",
    "master_action": "Capacitación planificada y seguimiento",
    "master_action_explanation": "Garantiza adaptación y crecimiento constante",
    "master_tool": "Matriz Avanzada de Capacitación",
    "master_tool_explanation": "Prioriza formación según impacto estratégico"
  },
  {
    "code": "RES-S8",
    "label": "Falta de Relevo",
    "decision": "Plan de Sucesión",
    "decision_explanation": "Garantizar continuidad ante ausencias",
    "action": "Identificar sustitutos críticos",
    "action_explanation": "Evita dependencia de personas clave",
    "tool": "Mapa de Relevo Crítico",
    "tool_explanation": "Visualiza roles críticos y planes de contingencia",
    "master_decision": "Sucesión Proactiva",
    "master_decision_explanation": "Blindar la empresa frente a ausencias",
    "master_action": "Identificar y preparar sustitutos",
    "master_action_explanation": "Permite escalabilidad sin riesgo",
    "master_tool": "Mapa Estratégico de Relevo",
    "master_tool_explanation": "Visualiza plan de sucesión y niveles de criticidad"
  },
  {
    "code": "RES-S9",
    "label": "Rigidez Organizativa",
    "decision": "Estructura Flexible",
    "decision_explanation": "Ajustar perfiles al rol natural",
    "action": "Simplificar organigrama y alinear roles",
    "action_explanation": "Aumenta eficiencia y agilidad operativa",
    "tool": "Organigrama Circular",
    "tool_explanation": "Representación dinámica de la estructura y flujos",
    "master_decision": "Adaptabilidad Organizativa",
    "master_decision_explanation": "Ajustar estructura a crecimiento",
    "master_action": "Reorganización por roles y procesos críticos",
    "master_action_explanation": "Facilita expansión ágil y reducción de cuellos de botella",
    "master_tool": "Organigrama Dinámico Circular",
    "master_tool_explanation": "Herramienta de modelado flexible para crecimiento"
  },
  {
    "code": "RES-S10",
    "label": "Onboarding de Alto Impacto",
    "decision": "Integración Acelerada",
    "decision_explanation": "Que nuevos rindan rápido sin depender del dueño",
    "action": "Manual de onboarding + auditoría de procesos",
    "action_explanation": "Reduce curva de aprendizaje y errores iniciales",
    "tool": "Protocolo de Onboarding",
    "tool_explanation": "Estandariza incorporación y entrega de conocimiento",
    "master_decision": "Integración Sostenible",
    "master_decision_explanation": "Nuevos operan al 100% rápidamente",
    "master_action": "Onboarding + auditoría + mentoring",
    "master_action_explanation": "Acelera contribución y reduce dependencia del dueño",
    "master_tool": "Protocolo Integral de Onboarding",
    "master_tool_explanation": "Estandariza incorporación con resultados medibles"
  },
  {
    "code": "TER-S1",
    "label": "Gigantismo Caótico",
    "decision": "Estructuración de Base",
    "decision_explanation": "Evitar que el crecimiento rompa la experiencia",
    "action": "Auditoría de procesos vs. carga nueva",
    "action_explanation": "Detecta puntos críticos que colapsan con más ventas",
    "tool": "Test de Estrés de Crecimiento",
    "tool_explanation": "Simula la capacidad operativa y visualiza cuellos de botella",
    "master_decision": "Escalabilidad Experta",
    "master_decision_explanation": "Crecer sin romper experiencia",
    "master_action": "Auditoría operativa + simulación de crecimiento",
    "master_action_explanation": "Garantiza que la experiencia se mantenga con mayores volúmenes",
    "master_tool": "Simulación de Estrés Operativo",
    "master_tool_explanation": "Modela impacto de incremento de clientes y procesos"
  },
  {
    "code": "TER-S2",
    "label": "Dilución de Cultura",
    "decision": "Protección de Esencia",
    "decision_explanation": "Mantener ADN y valores intactos",
    "action": "Manual de bienvenida y valores",
    "action_explanation": "Asegura coherencia de experiencia y cultura",
    "tool": "Onboarding de Cultura",
    "tool_explanation": "Documento de integración de nuevos clientes/empleados según valores",
    "master_decision": "Cultura Cohesiva",
    "master_decision_explanation": "Integrar valores en cada interacción",
    "master_action": "Onboarding omnicanal de clientes y equipo",
    "master_action_explanation": "Refuerza coherencia de marca y experiencia",
    "master_tool": "Playbook de Cultura",
    "master_tool_explanation": "Manual de aplicación práctica de valores en todos los canales"
  },
  {
    "code": "TER-S3",
    "label": "Fragilidad Estructural",
    "decision": "Refuerzo de Cimientos",
    "decision_explanation": "Preparar la operación antes de crecer",
    "action": "Identificar puestos críticos ante aumento de ventas",
    "action_explanation": "Garantiza continuidad sin sobrecarga de personal",
    "tool": "Mapa de Nodos Críticos",
    "tool_explanation": "Visualiza roles y procesos clave que podrían colapsar",
    "master_decision": "Resiliencia de Procesos",
    "master_decision_explanation": "Preparar estructura para picos de demanda",
    "master_action": "Identificación y refuerzo de nodos críticos",
    "master_action_explanation": "Reduce riesgo de quiebres operativos",
    "master_tool": "Mapa Estratégico de Nodos",
    "master_tool_explanation": "Visualización de procesos y roles clave con impacto estratégico"
  },
  {
    "code": "TER-S4",
    "label": "Obsesión por el Volumen",
    "decision": "Rentabilidad en Escala",
    "decision_explanation": "No vender más, vender mejor",
    "action": "Análisis costes variables en expansión",
    "action_explanation": "Maximiza margen sin comprometer experiencia",
    "tool": "Matriz de Escala Rentable",
    "tool_explanation": "Evalúa impacto económico de cada unidad de crecimiento",
    "master_decision": "Rentabilidad Inteligente",
    "master_decision_explanation": "Optimizar ganancias sin sacrificar experiencia",
    "master_action": "Optimización de costes vs. experiencia",
    "master_action_explanation": "Mantiene margen y satisfacción del cliente",
    "master_tool": "Matriz de Escala Rentable Avanzada",
    "master_tool_explanation": "Permite decisiones de expansión basadas en ROI real"
  },
  {
    "code": "TER-S5",
    "label": "Pérdida de Control",
    "decision": "Gobierno Remoto",
    "decision_explanation": "Gestionar sin presencia física",
    "action": "Cuadros de mando por sede/equipo",
    "action_explanation": "Permite supervisión de experiencia desde cualquier lugar",
    "tool": "Dashboard de Expansión",
    "tool_explanation": "Seguimiento centralizado de KPIs de experiencia y ventas",
    "master_decision": "Gestión Autónoma",
    "master_decision_explanation": "Supervisar sin depender de presencia",
    "master_action": "Dashboards integrales y alertas",
    "master_action_explanation": "Mantiene control de experiencia y KPIs críticos",
    "master_tool": "Cuadro de Mando Omnicanal",
    "master_tool_explanation": "Integración total de canales y sedes con métricas unificadas"
  },
  {
    "code": "TER-S6",
    "label": "Envejecimiento Prematuro",
    "decision": "Vigilancia de Mercado",
    "decision_explanation": "Mantener ventaja competitiva",
    "action": "Análisis tendencias y competidores",
    "action_explanation": "Detecta oportunidades de innovación antes que otros",
    "tool": "Radar de Innovación",
    "tool_explanation": "Herramienta de monitoreo de mercado y tendencias",
    "master_decision": "Innovación Constante",
    "master_decision_explanation": "Mantener ventaja competitiva sostenible",
    "master_action": "Análisis de tendencias y benchmarks",
    "master_action_explanation": "Permite anticipar cambios del mercado",
    "master_tool": "Radar Estratégico de Innovación",
    "master_tool_explanation": "Identifica oportunidades de mejora y diferenciación"
  },
  {
    "code": "TER-S7",
    "label": "Complejidad Innecesaria",
    "decision": "Simplificación Radical",
    "decision_explanation": "Reducir burocracia creada por crecimiento",
    "action": "Eliminar pasos innecesarios",
    "action_explanation": "Flujo más rápido y simple para el cliente",
    "tool": "Protocolo de Simplificación",
    "tool_explanation": "Guía para eliminar fricciones en procesos",
    "master_decision": "Flujo Simplificado",
    "master_decision_explanation": "Reducir pasos que no aportan valor",
    "master_action": "Reingeniería de procesos críticos",
    "master_action_explanation": "Experiencia más rápida y fluida para clientes",
    "master_tool": "Protocolo de Simplificación Avanzado",
    "master_tool_explanation": "Guía de eliminación de fricciones y redundancias"
  },
  {
    "code": "TER-S8",
    "label": "Falta de Sucesión",
    "decision": "Continuidad del Legado",
    "decision_explanation": "Preparar la empresa para el relevo",
    "action": "Formar 'herederos de gestión'",
    "action_explanation": "Asegura operación sin dependencia de fundadores",
    "tool": "Plan de Sucesión Sostenible",
    "tool_explanation": "Define roles y capacitación de sucesores",
    "master_decision": "Relevo Estratégico",
    "master_decision_explanation": "Preparar la próxima generación de líderes",
    "master_action": "Programa de desarrollo de sucesores",
    "master_action_explanation": "Garantiza continuidad operativa sin pérdida de calidad",
    "master_tool": "Plan Integral de Sucesión",
    "master_tool_explanation": "Define roles, capacitación y seguimiento de sucesores"
  },
  {
    "code": "TER-S9",
    "label": "Gestión del Activo Intelectual",
    "decision": "Retener conocimiento crítico",
    "decision_explanation": "Documentar procesos y saber hacer",
    "action": "Documentar procesos y saber hacer",
    "action_explanation": "Permite replicar procesos y escalar sin pérdida de know-how",
    "tool": "Wiki / Manual de Activos",
    "tool_explanation": "Centraliza información clave y protocolos",
    "master_decision": "Protección del Know-how",
    "master_decision_explanation": "Documentar todo conocimiento crítico",
    "master_action": "Sistema centralizado de gestión de activos",
    "master_action_explanation": "Escalabilidad sin pérdida de información",
    "master_tool": "Wiki Estratégico / Manual Maestro",
    "master_tool_explanation": "Repositorio vivo y actualizado de procesos y buenas prácticas"
  },
  {
    "code": "TER-S10",
    "label": "Incremento Propiedad",
    "decision": "Alineación de Coherencia",
    "decision_explanation": "Consolidar la comunidad y fidelización",
    "action": "Revisión trimestral de valores e hitos",
    "action_explanation": "Mantiene experiencia consistente y medible",
    "tool": "Brújula de Coherencia S10",
    "tool_explanation": "Seguimiento de la coherencia entre estrategia y experiencia",
    "master_decision": "Experiencia Sello",
    "master_decision_explanation": "Transformar clientes en promotores activos",
    "master_action": "Revisión de valores y consolidación de comunidad",
    "master_action_explanation": "Mantiene coherencia y reputación de marca",
    "master_tool": "Brújula de Coherencia Estratégica",
    "master_tool_explanation": "Herramienta de seguimiento y ajuste de experiencia a largo plazo"
  },
  {
    "code": "OPE-S1",
    "label": "Aprendizaje lento",
    "decision": "Mejorar sistema de aprendizaje",
    "decision_explanation": "Convertir los errores en oportunidades de mejora continua",
    "action": "Implementar revisión post-incidencia",
    "action_explanation": "Registrar, analizar y aplicar cambios tras cada fallo",
    "tool": "Registro de Incidencias",
    "tool_explanation": "Documenta cada fallo y las mejoras aplicadas para aprendizaje sistemático",
    "master_decision": "Activar aprendizaje automático",
    "master_decision_explanation": "El sistema debe usar los errores para mejorar",
    "master_action": "Implementar seguimiento de incidencias",
    "master_action_explanation": "Registrar y analizar fallos para ajustar procesos",
    "master_tool": "Sistema de Registro de Incidencias",
    "master_tool_explanation": "Permite rastrear y aprender de cada error"
  },
  {
    "code": "OPE-S2",
    "label": "Dependencia del dueño",
    "decision": "Fomentar autonomía del sistema",
    "decision_explanation": "Permitir que la empresa funcione sin supervisión constante",
    "action": "Delegar y automatizar procesos críticos",
    "action_explanation": "Identificar y transferir tareas repetitivas a procesos autónomos",
    "tool": "Dashboard de Autonomía",
    "tool_explanation": "Permite medir cuánto del negocio funciona sin intervención del dueño",
    "master_decision": "Autonomizar procesos",
    "master_decision_explanation": "Reducir supervisión directa del líder",
    "master_action": "Delegar tareas críticas",
    "master_action_explanation": "Que el equipo opere sin intervención constante",
    "master_tool": "Dashboard de Autonomía",
    "master_tool_explanation": "Monitorea la ejecución de tareas sin depender del dueño"
  },
  {
    "code": "OPE-S3",
    "label": "Fricción en canales híbridos",
    "decision": "Sincronizar procesos físicos y digitales",
    "decision_explanation": "Garantizar experiencia uniforme entre online y offline",
    "action": "Establecer protocolos de traspaso",
    "action_explanation": "Crear flujos estandarizados entre web y local",
    "tool": "Checklist de Sincronía",
    "tool_explanation": "Herramienta para validar la correcta transición entre canales",
    "master_decision": "Sincronizar híbrido",
    "master_decision_explanation": "Evitar errores al pasar de digital a físico",
    "master_action": "Revisar flujos híbridos",
    "master_action_explanation": "Asegurar que las tareas se transfieran correctamente",
    "master_tool": "Mapa de Flujo Omnicanal",
    "master_tool_explanation": "Visualiza y corrige los puntos de fricción entre canales"
  },
  {
    "code": "OPE-S4",
    "label": "Re-trabajo frecuente",
    "decision": "Reducir desperdicio",
    "decision_explanation": "Evitar errores por falta de claridad o instrucción",
    "action": "Implementar entregas First-Time",
    "action_explanation": "Estandarizar procesos y controles para entregar correctamente a la primera",
    "tool": "Lean Workflow",
    "tool_explanation": "Visualiza flujos y elimina pasos innecesarios para optimizar eficiencia",
    "master_decision": "Cero desperdicio",
    "master_decision_explanation": "Eliminar reprocesos innecesarios",
    "master_action": "Aplicar entregas First-Time",
    "master_action_explanation": "Garantizar que el trabajo salga correcto a la primera",
    "master_tool": "Checklists Lean",
    "master_tool_explanation": "Establece pasos claros para entregas perfectas"
  },
  {
    "code": "OPE-S5",
    "label": "Incapacidad para absorber picos",
    "decision": "Incrementar elasticidad operativa",
    "decision_explanation": "Manejar aumentos de demanda sin colapsar",
    "action": "Ajustar recursos en picos",
    "action_explanation": "Redistribuir personal y procesos para responder a demandas altas",
    "tool": "Plan de Escalabilidad",
    "tool_explanation": "Simula escenarios de aumento de demanda y evalúa capacidad de respuesta",
    "master_decision": "Elasticidad operativa",
    "master_decision_explanation": "Absorber aumentos sin colapsar",
    "master_action": "Ajustar recursos y procesos",
    "master_action_explanation": "Preparar sistemas para escalabilidad",
    "master_tool": "Indicadores de Elasticidad",
    "master_tool_explanation": "Mide capacidad de respuesta frente a picos"
  },
  {
    "code": "OPE-S6",
    "label": "Fallos de suministro",
    "decision": "Mejorar precisión de suministro",
    "decision_explanation": "Garantizar que los materiales lleguen completos y a tiempo",
    "action": "Validar proveedores y seguimiento",
    "action_explanation": "Control estricto de entregas y cumplimiento de proveedores",
    "tool": "Control de Suministro",
    "tool_explanation": "Registra y verifica la calidad y puntualidad de los proveedores",
    "master_decision": "Control de calidad",
    "master_decision_explanation": "Evitar que proveedores frenen la operación",
    "master_action": "Monitorizar entregas",
    "master_action_explanation": "Detectar desviaciones y corregir rápidamente",
    "master_tool": "Panel de Suministro",
    "master_tool_explanation": "Visualiza cumplimiento de proveedores en tiempo y forma"
  },
  {
    "code": "OPE-S7",
    "label": "Poco desarrollo creativo",
    "decision": "Fomentar cultura de innovación",
    "decision_explanation": "Incentivar propuestas de mejora del equipo",
    "action": "Crear programa de ideas rentables",
    "action_explanation": "Premiar y ejecutar ideas que aporten valor",
    "tool": "Mapa de Innovación",
    "tool_explanation": "Herramienta para registrar ideas, evaluar impacto y seguimiento",
    "master_decision": "Innovación interna",
    "master_decision_explanation": "El equipo debe generar mejoras",
    "master_action": "Incentivar propuestas rentables",
    "master_action_explanation": "Capturar ideas que aumenten beneficio",
    "master_tool": "Registro de Propuestas",
    "master_tool_explanation": "Permite registrar, evaluar y medir ideas de la plantilla"
  },
  {
    "code": "OPE-S8",
    "label": "Vulnerabilidad ante rotación",
    "decision": "Blindar procesos críticos",
    "decision_explanation": "Evitar pérdida de know-how por cambios de personal",
    "action": "Establecer backups de procesos",
    "action_explanation": "Capacitar a varias personas en procesos clave",
    "tool": "Manual de Procesos",
    "tool_explanation": "Documenta cada proceso vital para asegurar continuidad ante bajas",
    "master_decision": "Blindaje de procesos",
    "master_decision_explanation": "Mantener know-how ante cambios",
    "master_action": "Documentar procesos con backups",
    "master_action_explanation": "Asegurar que varias personas dominan cada tarea",
    "master_tool": "Manual de Procesos Críticos",
    "master_tool_explanation": "Respalda conocimiento clave de la empresa"
  },
  {
    "code": "OPE-S9",
    "label": "Trabajo repetitivo manual",
    "decision": "Digitalizar tareas",
    "decision_explanation": "Liberar al humano para tareas estratégicas",
    "action": "Implementar automatización inteligente",
    "action_explanation": "Software o scripts para tareas repetitivas",
    "tool": "Sistema de Automatización",
    "tool_explanation": "Plataforma que permite programar, monitorizar y ejecutar tareas automáticas",
    "master_decision": "Automatización inteligente",
    "master_decision_explanation": "Liberar al humano de tareas sin valor",
    "master_action": "Implementar software/IA",
    "master_action_explanation": "Digitalizar procesos repetitivos",
    "master_tool": "Plataforma de Automatización",
    "master_tool_explanation": "Ejecuta tareas automáticamente, reduciendo errores y tiempo"
  },
  {
    "code": "OPE-S10",
    "label": "Dependencia del dueño para resultados",
    "decision": "Validar que el negocio mantiene productividad",
    "decision_explanation": "Que la empresa funcione perfectamente sin supervisión",
    "action": "Medir resultados en ausencia del dueño",
    "action_explanation": "Comparar desempeño con y sin la presencia del dueño",
    "tool": "Panel de Performance Post-Dueño",
    "tool_explanation": "Mide la autonomía operativa y la capacidad del negocio de generar valor sin intervención",
    "master_decision": "Auditoría de Robustez Operativa",
    "master_decision_explanation": "Comprobar la resistencia de procesos críticos frente a variaciones de operación",
    "master_action": "Testar sistemas y procesos ante escenarios límite",
    "master_action_explanation": "Identifica puntos débiles y asegura continuidad operativa",
    "master_tool": "Checklist de Stress Test Operativo",
    "master_tool_explanation": "Verifica que procesos críticos mantienen eficiencia y fiabilidad"
  }
]

@router.get("/ping")
def ping():
    return {"status": "ok"}
@router.get("/symptom-master/", response_model=list[SymptomMaster])
async def get_symptom_master():
    collection = get_collection("symptom_master")
    cursor = collection.find({})
    docs = await cursor.to_list(length=1000)
    return [SymptomMaster(**d) for d in docs]

@router.get("/by-department/{department}", response_model=List[SymptomMaster])
async def list_by_department(department: str):
    collection = get_collection("symptom_master")
    cursor = collection.find({"department": department.upper()})
    docs = await cursor.to_list(length=1000)
    return [SymptomMaster(**d) for d in docs]

@router.post("/symptom-master/seed")
async def seed_symptom_master():
    collection = get_collection("symptom_master")
    existing = await collection.count_documents({})
    if existing > 0:
        return {"message": "Collection already seeded", "count": existing}
    await collection.insert_many(ALL_SYMPTOMS)
    return {"message": "Seeded successfully", "count": len(ALL_SYMPTOMS)}