SPECIALTY_TO_DEPARTMENT = {
    "UCI FINANCIERA": "FINANZAS",
    "UNIDAD DE PROCESOS": "PROCESOS",
    "CARDIOLOGIA COMERCIAL": "COMERCIAL",
    "NEUROLOGIA ESTRATÉGICA": "ESTRATÉGIA",
    "GESTION CLINICA": "GESTION",
    "CIRUJIA DE MARCA": "MARCA",
    "PSIQUIATRÍA ORGANIZACIONAL": "ORGANIZACIONAL",
    "RESCATE DEPERSONAS": "PERSONAS",
    "TERAPIA DE EXPERIENCIA": "EXPERIENCIA",
    "EXCELENCIA OPERATIVA": "EXCELENCIA"
}